// astro/src/components/SignUp.svelte
<script>
    import InputField from './forms/InputField.svelte';
    import SubmitButton from './forms/SubmitButton.svelte';

    function handleSubmit(event) {
        event.preventDefault();

        const formData = {
            username: event.target.username.value,
            password: event.target.password.value,
            passwordConfirm: event.target.passwordConfirm.value,
        };

        // validate form data

        fetch('/sign-up', {
            method: 'post',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(formData),
        }).then((res) => {
            window.location = '/home';
        });
    }
</script>

<div class="wrapper">
    <h1>Sign Up</h1>
    <p>Already have an account?<br />Log in <a href="/login">here</a></p>
    <form on:submit={handleSubmit}>
        <InputField type="text" label="Username" name="username" placeholder="username" />
        <InputField type="password" label="Password" name="password" placeholder="password" />
        <InputField type="password" label="Confirm Password" name="passwordConfirm" placeholder="password" />
        <SubmitButton text="Sign Up" />
    </form>
</div>

<style>
    a {
        color: rgb(162, 186, 255);
    }

    p {
        margin-top: 40px;
    }

    form {
        margin-top: 40px;
    }
</style>

// client/src/components/SignUp.jsx
import React, { useEffect, useState } from 'react';

function SignUp() {
    const [errorMessages, setErrorMessages] = useState({});

    function renderErrorMessage(name) {
        // console.log(errorMessages.name);
        return name === errorMessages.name && <div className="error">{errorMessages.message}</div>;
    }

    const handleSubmit = (event) => {
        event.preventDefault();
        const { usernameInput, passwordInput } = document.forms[0];

        fetch('http://localhost:3001/api/users/' + usernameInput.value, { method: 'GET' })
            .then((res) => {
                return res.json();
            })
            .then((data) => {
                console.log(data)
                if (Object.keys(data).length !== 0) {
                    setErrorMessages({
                        name: 'username-input',
                        message: 'Username already taken',
                    });
                    return;
                }
                const requestOptions = {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ username: usernameInput.value, password: passwordInput.value }),
                };
                fetch('http://localhost:3001/api/users', requestOptions)
                    .then((res) => {
                        return res.json();
                    })
                    .then((info) => {});
            });
    };

    return (
        <div>
            <h1>Sign-up</h1>
            <a href="/">Home</a>
            <br />
            <br />
            <div className="form">
                <form onSubmit={handleSubmit}>
                    <div className="input-container">
                        <label>Username</label>
                        <br />
                        <input type="text" name="usernameInput" required />
                        {renderErrorMessage('username-input')}
                    </div>
                    <br />
                    <div className="input-container">
                        <label>Password</label>
                        <br />
                        <input type="password" name="passwordInput" required />
                        {renderErrorMessage('password-input')}
                    </div>
                    <br />
                    <div className="input-container">
                        <label>Confirm password</label>
                        <br />
                        <input type="password" name="confirm-password-input" required />
                        {renderErrorMessage('confirm-password-input')}
                    </div>
                    <br />
                    <div className="button-container">
                        <input type="submit" value="Sign up" />
                    </div>
                </form>
            </div>
        </div>
    );
}

export default SignUp;
